language: generic
sudo: required
services:
    - docker

before_install:
    -  docker build -t cetauri/react-docker -f Dockerfile.dev .

    script:
        -  docker run -e CI=true cetauri/react-docker npm run test

