language: generic
sudo: required
services:
    - docker

before_install:
    -  docker build -t cetauri/react-docker -f Dockerfile.dev .

script:
    -  docker run -e CI=true cetauri/react-docker npm run test


deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-central-1-264477463968"
    bucket_path: "docker-react"
    on:
        branch: "master"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

